name: CI/CD for Flutter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: 3.13.6

      - name: Install dependencies
        run: flutter pub get

      - name: Build and Deploy
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY_JSON" > firebase-token.json
          firebase deploy --token "$(cat firebase-token.json)"
