name: CI/CD for Flutter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.6

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0

      - name: Install dependencies
        run: flutter pub get

      - name: Build and Deploy
        run: |
          # Authenticate with Firebase using the provided service account key JSON
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY_JSON" > firebase-token.json
          npx firebase login:ci --token "$FIREBASE_SERVICE_ACCOUNT_KEY_JSON" # Use npx to run Firebase CLI

          # Deploy to Firebase Hosting
          npx firebase deploy --token "$(cat firebase-token.json)"
